### ISSUE TITLE
GitHub issue detected from wrong repo

### ISSUE THREAD

**Issue by akoeplinger** [chamons/clio#31]
E.g. https://github.com/mono/mono/commit/ff76904cbe7f47b76c064f277e587b058a2f62b3 is detected as having fixed Mono GitHub issue `#1093` but it is actually from another repo.

**Comment by chamons** [comment]
This should be fixed by https://github.com/chamons/clio/pull/60/commits/2c9738180c474c70696976178ffd57a6d8df035d now
