### ISSUE TITLE
Some comments from 15.8 preview 1

### ISSUE THREAD

**Issue by spouliot** [chamons/clio#50]
Based on the list of xamarin-macios issues I added some comments on how `clio` could have produced a more accurate list
https://gist.github.com/chamons/4965fbcbf3df2ad0a074ebbf59b2f367

**Comment by chamons** [comment]
Some of this are no longer valid, given bugzilla is dead, but I extracted these three bugs.

- [Should look for backports](https://github.com/chamons/clio/issues/64)
- [Should have option to skip commit messages with some tag ([test][tests][xharness])](https://github.com/chamons/clio/issues/63)
- [Should list cross repro as lower not ignore?](https://github.com/chamons/clio/issues/62)
